In [1]:
from heavylight import Table
import pandas as pd
import numpy as np
# typically you would import the table from a csv or other source

df = pd.DataFrame(
  {'age|int': np.arange(18, 66)}
)
df['values'] = df['age|int'] * 0.01

tab = Table(df)

# we can query a single value
print(tab[20])   # prints(0.20)

# we can query multiple values at once using numpy arrays.
rng = np.random.default_rng(seed=42)   # set up random number generator
ages = rng.integers(low=18, high=65, size=100_000, endpoint=True)   # sample 100k ages
vals = tab[ages]    # query the table and store values
vals

0.2


array([0.22, 0.55, 0.49, ..., 0.45, 0.18, 0.62])

In [2]:
np.histogram(vals)

(array([10416, 10401, 10461,  8272, 10361, 10384,  8445, 10528, 10377,
        10355]),
 array([0.18 , 0.227, 0.274, 0.321, 0.368, 0.415, 0.462, 0.509, 0.556,
        0.603, 0.65 ]))