In [1]:
import heavylight
import pandas as pd
import numpy as np

# A Vectorised Actuarial Contingency Model

In [2]:
class Life(heavylight.Model):
    time_step = 1/12
    def num_pols_if(self, t):
        if t == 0:
            return self.data["initial_policies"]
        else:
            return self.num_pols_if(t - 1) - self.num_deaths(t - 1)
    
    def num_deaths(self, t):
        return self.num_pols_if(t) * self.q_x_m(t)
    
    def age(self, t):
        """age at time t"""
        if t == 0:
            return self.data["initial_age"] # floating point
        else:
            return self.age(t - 1) + Life.time_step
    
    def age_rounded(self, t):
        return np.round(self.age(t)).astype(int)
    
    def q_x_m(self, t):
        """monthly mortality rate"""
        return self.q_x(t) ** (Life.time_step)
    
    def q_x(self, t):
        """annual mortality rate"""
        return self.basis["mortality"][self.age_rounded(t)]

In [3]:
ages = np.array([32+1/12, 42, 25+7/12])
ages

array([32.08333333, 42.        , 25.58333333])

In [4]:
ages ** 1/12

array([2.67361111, 3.5       , 2.13194444])

In [5]:
mortality = heavylight.Table.read_csv("sample_q_x_table.csv")

In [6]:
mortality[np.array([20, 21])]

array([0.141392  , 0.14691122])

In [7]:
basis = {"mortality": mortality}

In [8]:
num_model_points = 3
data = {
    "initial_policies": np.ones(num_model_points),
    "initial_age" : np.array([32+1/12, 42, 25+7/12]),
    }

In [9]:
model = Life(data=data, basis=basis)

In [10]:
model.num_pols_if(2)

array([0.01372978, 0.0078071 , 0.01795082])

In [11]:
model.num_pols_if(20)
model.df

age   age_rounded  \
0      [32.083333333333336, 42.0, 25.583333333333332]  [32, 42, 26]   
1   [32.16666666666667, 42.083333333333336, 25.666...  [32, 42, 26]   
2   [32.25000000000001, 42.16666666666667, 25.7499...  [32, 42, 26]   
3   [32.33333333333334, 42.25000000000001, 25.8333...  [32, 42, 26]   
4   [32.41666666666668, 42.33333333333334, 25.9166...  [32, 42, 26]   
5   [32.500000000000014, 42.41666666666668, 25.999...  [33, 42, 26]   
6   [32.58333333333335, 42.500000000000014, 26.083...  [33, 43, 26]   
7   [32.666666666666686, 42.58333333333335, 26.166...  [33, 43, 26]   
8   [32.75000000000002, 42.666666666666686, 26.249...  [33, 43, 26]   
9   [32.83333333333336, 42.75000000000002, 26.3333...  [33, 43, 26]   
10  [32.91666666666669, 42.83333333333336, 26.4166...  [33, 43, 26]   
11  [33.00000000000003, 42.91666666666669, 26.4999...  [33, 43, 26]   
12  [33.083333333333364, 43.00000000000003, 26.583...  [33, 43, 27]   
13  [33.1666666666667, 43.083333333333364, 26.6666...  [33, 43, 27]   
14  [33.250000000000036, 43.1666666666667, 26.7499...  [33, 43, 27]   
15  [33.33333333333337, 43.250000000000036, 26.833...  [33, 43, 27]   
16  [33.41666666666671, 43.33333333333337, 26.9166...  [33, 43, 27]   
17  [33.50000000000004, 43.41666666666671, 26.9999...  [34, 43, 27]   
18  [33.58333333333338, 43.50000000000004, 27.0833...  [34, 44, 27]   
19  [33.666666666666714, 43.58333333333338, 27.166...  [34, 44, 27]   

                                           num_deaths  \
0   [0.8828258515777705, 0.9116422250059119, 0.866...   
1   [0.10344436736375484, 0.08055067859218223, 0.1...   
2   [0.01212100565492424, 0.007117278734669153, 0....   
3   [0.0014202685156367758, 0.0006288669130081055,...   
4   [0.00016641875385064311, 5.556528120079702e-05...   
5   [1.956262436532288e-05, 4.909624613823256e-06,...   
6   [2.2367483557387096e-06, 4.3520115381033597e-0...   
7   [2.5574499174907855e-07, 3.717514659299149e-08...   
8   [2.924133179171842e-08, 3.17552357596159e-09, ...   
9   [3.3433909266629584e-09, 2.7125515043399913e-1...   
10  [3.822761209411824e-10, 2.317077951930832e-11,...   
11  [4.370862870878672e-11, 1.979262044143309e-12,...   
12  [4.9975505111304544e-12, 1.690697646197833e-13...   
13  [5.714091667735037e-13, 1.4442041867660465e-14...   
14  [6.533369400581272e-14, 1.2336479782550785e-15...   
15  [7.470113923001032e-15, 1.0537895875103027e-16...   
16  [8.541167443807653e-16, 9.001534589436364e-18,...   
17  [9.797172522199287e-17, 7.689165458187552e-19,...   
18  [1.0923012951583584e-17, 6.589298082177608e-20...   
19  [1.2178229144185705e-18, 5.434411964595892e-21...   

                                          num_pols_if  \
0                                     [1.0, 1.0, 1.0]   
1   [0.11717414842222951, 0.08835777499408815, 0.1...   
2   [0.013729781058474666, 0.007807096401905911, 0...   
3   [0.0016087754035504255, 0.0006898176672367577,...   
4   [0.00018850688791364968, 6.0950754228652235e-0...   
5   [2.208813406300657e-05, 5.385473027855218e-06,...   
6   [2.5255096976836874e-06, 4.758484140319622e-07...   
7   [2.8876134194497785e-07, 4.064726022162622e-08...   
8   [3.30163501958993e-08, 3.4721136286347324e-09,...   
9   [3.77501840418088e-09, 2.965900526731422e-10, ...   
10  [4.3162747751792177e-10, 2.533490223914309e-11...   
11  [4.935135657673935e-11, 2.1641227198347674e-12...   
12  [5.642727867952626e-12, 1.8486067569145844e-13...   
13  [6.451773568221717e-13, 1.579091107167514e-14,...   
14  [7.376819004866793e-14, 1.3488692040146744e-15...   
15  [8.43449604285521e-15, 1.1522122575959584e-16,...   
16  [9.643821198541772e-16, 9.842267008565579e-18,...   
17  [1.1026537547341186e-16, 8.407324191292148e-19...   
18  [1.2293650251418988e-17, 7.181587331045959e-20...   
19  [1.3706372998354035e-18, 5.922892488683514e-21...   

                                                  q_x  \
0   [0.224130264787305, 0.3295286574691513, 0.1779...   
1   [0.224130264787305, 0.3295286574691513, 0.17